name = "lamiglowki"
compatibility_date = "2025-01-10"
pages_build_output_dir = ".vercel/output/static"

compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages@1"

[env.production]
compatibility_flags = ["nodejs_compat"]
